### ISSUE TITLE
Feed UI Checklist

### ISSUE THREAD

**Issue by vapurrmaid** [vapurrmaid/Quizzr#25]
- [x] UI specs
- [x] Remove tabs from header component and move to feed component
- [x] AJAX actions to /api/quizzes
- [x] Populate feed container with request results
- [x] Quizzes have hashtags
