### ISSUE TITLE
Quiz View Checklist

### ISSUE THREAD

**Issue by vapurrmaid** [vapurrmaid/Quizzr#26]
- [x] Wireframe/Spec Quiz View
- [x] Create the React/Redux View (use redux form?)
- [x] Quiz View Properly Shows the Author that created the quiz
