### ISSUE TITLE
Client Side Authentication Checklist

### ISSUE THREAD

**Issue by vapurrmaid** [vapurrmaid/Quizzr#8]
Implement all necessary steps for client-side authentication:
- [x] Setup Server Cors
- [x] Client proxy ? 
- [x] sigin form
- [x] signup form
- [x] signout
- [x] Protect/Authenticate client routes #16 
- [ ] store tokens and append to subsequent requests
- [x] automatic authentication #17 
- [x] error handling/useful messages
- [x] update header links #9

**Comment by vapurrmaid** [comment]
#16 Will Protect routes
